name: Execute EMA Bot From External Cron

on:
  # Mở cổng nhận tín hiệu kích hoạt từ trang web cron-job.org bên ngoài
  workflow_dispatch:

jobs:
  run-ema-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn từ Repository
        uses: actions/checkout@v4

      - name: Khởi tạo môi trường Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cài đặt thư viện dependencies
        run: npm install

      - name: Thực thi Script ema.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node ema.js

      - name: Commit & Push file log sent_ema.json thay đổi
        run: |
          # Cấu hình danh tính Git ẩn danh của GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Chỉ add file log chống trùng để theo dõi countdown
          git add sent_ema.json
          
          # Chỉ tiến hành commit và push nếu thực sự có tín hiệu mới được lưu vào log
          if git diff --cached --quiet; then
            echo "Không có file log nào thay đổi. Bỏ qua bước Git Push."
          else
            git commit -m "🤖 [Bot Action] Cập nhật bộ đếm ngược chống trùng lệnh sent_ema.json [skip ci]"
            git push origin HEAD:${{ github.ref }}
          fi
